### ISSUE TITLE
clear console logs

### ISSUE THREAD

**Issue by thepranaygupta** [aec-coding-club/AEC-Coding-Club-Website#34]
clear all console logs that expose sensitive data in the browser console

**Comment by saikatmu31** [comment]
@thepranaygupta Sir Please Assign it to @saikatmu31 and @8-bit-souvik we are just starting with Open Source Contribution

**Comment by thepranaygupta** [comment]
> @thepranaygupta Sir Please Assign it to @saikatmu31 and @8-bit-souvik we are just starting with Open Source Contribution

do you also want to contribute to hacktoberfest?

**Comment by thepranaygupta** [comment]
assigned to @saikatmu31 and @8-bit-souvik 🚀

**Comment by 8-bit-souvik** [comment]
> > @thepranaygupta Sir Please Assign it to @saikatmu31 and @8-bit-souvik we are just starting with Open Source Contribution
> 
> do you also want to contribute to hacktoberfest?

sir can we bring it to Google Summer of Code? 🙂

**Comment by 8-bit-souvik** [comment]
> > @thepranaygupta Sir Please Assign it to @saikatmu31 and @8-bit-souvik we are just starting with Open Source Contribution
> 
> do you also want to contribute to hacktoberfest?

@thepranaygupta  Sir, can we bring it to Google Summer of Code? 🙂
