### ISSUE TITLE
reorder members page

### ISSUE THREAD

**Issue by thepranaygupta** [aec-coding-club/AEC-Coding-Club-Website#37]
also fix the LinkedIn link of `Anupriya Kumari` in `members.js` from `linkedin.com/in/anupriya-kumari-25ab621b` to `https://www.linkedin.com/in/anupriya-kumari-25ab621b`

![image](https://user-images.githubusercontent.com/64855541/157398087-39acaa00-6a2e-483d-b444-f209a29d6dd7.png)

**Comment by RishiKumarRay** [comment]
@thepranaygupta can you elaborate the members pages needs to be reordered.

**Comment by Abirpal202049** [comment]
> @thepranaygupta can you elaborate on the member's pages that need to be reordered.

Sorry Bro this is our college project so we cant assign this task you may try to solve some other's issue
